org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod Properties
mod_id=witherstorm_delight
mod_name=Wither Storm Delight
mod_license=MIT License
mod_version=1.0.0
mod_group_id=show.wsd.mod
mod_authors=shuixingshow, Vzling, gengyoubo
mod_description=This mod adds more Farmer's Delight style food and tools to Cracker's Wither Storm mod